name: account_statement
description: A new Flutter module.
version: 1.0.0+1
homepage: https://github.com/jiangyang5157/account-statement

environment:

  sdk: ">=2.1.0 <3.0.0"

dependencies:

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application
  cupertino_icons: ^0.1.3

  # Simple direct Service Locator that allows to decouple the interface from a concrete implementation and to access the concrete implementation from everywhere in your App
  get_it: ^4.0.2

  # Value equality
  equatable: ^1.2.0

  # Classes and helper functions that support JSON code generation via the `json_serializable` package
  json_annotation: ^3.0.1

  # Flutter routing library that adds flexible routing options
  fluro: ^1.6.3

  # Flutter plugin for reading and writing simple key-value pairs. Wraps NSUserDefaults on iOS and SharedPreferences on Android
#  shared_preferences: ^0.5.7+3

  # Flutter Secure Storage provides API to store data in secure storage. Keychain is used in iOS, KeyStore based solution is used in Android.
#  flutter_secure_storage: ^3.3.3

  # State management
#  provider: ^4.1.3

  # Functional programming things
#  dartz: ^0.9.1

  # Material Design data visualization library written natively in Dart
  charts_flutter: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Automatically generate code for converting to and from JSON by annotating Dart classes.
  json_serializable: ^3.3.0

  # The build_runner package provides a concrete way of generating files using Dart code, outside of tools like pub.
  # Unlike pub serve/build, files are always generated directly on disk, and rebuilds are incremental - inspired by tools such as Bazel.
  build_runner: ^1.10.0

flutter:
  # The following line ensures that the Material Icons font is included with your application
  uses-material-design: true

  # To add Flutter specific assets to your application, add an assets section
  assets:
    - res/values/strings.json

  # This section identifies your Flutter project as a module meant for
  # embedding in a native host app.  These identifiers should _not_ ordinarily
  # be changed after generation - they are used to ensure that the tooling can
  # maintain consistency when adding or modifying assets and plugins.
  # They also do not have any bearing on your native host application's
  # identifiers, which may be completely independent or the same as these.
  module:
    androidX: true
    androidPackage: com.gmail.jiangyang5157.account_statement
    iosBundleIdentifier: com.gmail.jiangyang5157.accountStatement
